Blog post for Contributor Celebration 2021
kubernetes/contributor-site pull request #265
Opened 2021-12-06 18:33 UTC by Debanitrkl

This PR is regarding the blogpost for contributor celebration 2021, the draft could be found [here](https://hackmd.io/@XzECIhDGRqCtGVrLiJFzxQ/BkUtTYwFY/edit)

2021-12-06 22:02 UTC, jberkus commented on content/en/blog/2021/contributor-celebration.md
> +If you have any questions or concerns, please visit [here](https://www.kubernetes.dev/events/kcc2021/faq/). Also don't forget to [register if you're interested](https://forms.gle/oAppmLDggEEGx5tz5) a
```suggestion
If you have any questions or concerns, please visit [here](https://www.kubernetes.dev/events/kcc2021/faq/). Also don't forget to [register if you're interested](https://forms.gle/oAppmLDggEEGx5tz5) as well as bookmark the 2021 [Kubernetes Contributor Celebration landing page](https://k8s.dev/celebration) for updated details between now and the celebration.
```

2021-12-06 22:11 UTC, jberkus requested changes

2021-12-06 22:11 UTC, jberkus commented on content/en/blog/2021/contributor-celebration.md
> +     In this special event we honor and dedicate the hard work that the community has been working on. These peer awards are a tradition at the Kubernetes Contributor Summits so we are bringing them
```suggestion
     In this special event we honor contributors who have made special efforts, or shown extraordinary ability, during the prior year. These peer awards are a tradition at the Kubernetes Contributor Summits, and this year we're having them online. Please join us to thank and support fellow contributors who have made our project excellent.
```

2021-12-06 22:11 UTC, jberkus commented on content/en/blog/2021/contributor-celebration.md
> +    Contestants will have 90 minutes to cook a Kubernetes themed dessert. Anything goes, as long as the majority of preparation is done live.  The competition is open to all skill levels, from baking
```suggestion
    Contestants will have 90 minutes to bake something related to to your Cloud Native experience. Anything goes, as long as the majority of preparation is done live.  The competition is open to all skill levels, from baking from a cake mix to grinding your own flour as long as it's somehow Kubernetes-themed.
```

2021-12-06 22:11 UTC, jberkus commented on content/en/blog/2021/contributor-celebration.md
> +    A virtual cooking event styled after the [Great British Bake-off](https://en.wikipedia.org/wiki/The_Great_British_Bake_Off) will be held during the Kubernetes celebration Event
```suggestion
    A virtual cooking event styled after the [Great British Bake-off](https://en.wikipedia.org/wiki/The_Great_British_Bake_Off) will be held during the Kubernetes celebration Event.
```

2021-12-06 22:11 UTC, jberkus commented on content/en/blog/2021/contributor-celebration.md
> +    Our Host and Commentators will provide commentary on our contestants and will ask each contestant questions throughout the event.
please cut these three lines, it's too much detail, and is covered better by the form header.

2021-12-06 22:11 UTC, jberkus commented on content/en/blog/2021/contributor-celebration.md
> +    3. Taste: Obviously the judges can’t taste it, so they’ll need to be creative for this one.
```suggestion
At the end of the contest, each baked good will be judged on ambition, execution, success, and implementation of a Kubernetes theme.  The winner will get a unique, handmade, baking-related prize.
```

2021-12-07 00:08 UTC, mrbobbytables requested changes

2021-12-07 00:08 UTC, mrbobbytables commented on content/en/blog/2021/contributor-celebration.md
> +If you have any questions or concerns, please visit [here](https://www.kubernetes.dev/events/kcc2021/faq/). Also don't forget to [register if you're interested](https://forms.gle/oAppmLDggEEGx5tz5) a
```suggestion
If you have any questions or concerns, please see the [faq](/events/kcc2021/faq/). Also don't forget to [register if you're interested](https://forms.gle/oAppmLDggEEGx5tz5) as well as bookmark the 2021 [Kubernetes Contributor Celebration landing page](https://k8s.dev/celebration) for updated details between now and the celebration.
```

2021-12-07 13:27 UTC, mrbobbytables reviewed
Mostly formatting changes from previous suggestion 👍

2021-12-07 13:27 UTC, mrbobbytables commented on content/en/blog/2021/contributor-celebration.md
> +4. **krafternetes**
```suggestion
4. **[krafternetes](/events/kcc2021/activities/#krafternetes)**
```

2021-12-07 13:27 UTC, mrbobbytables commented on content/en/blog/2021/contributor-celebration.md
> +3. [**Kubernetes Contributor Awards**](https://www.kubernetes.dev/events/kcc2021/activities/#kubernetes-contributor-awards)
```suggestion
3. [**Kubernetes Contributor Awards**](/events/kcc2021/activities/#kubernetes-contributor-awards)
```

2021-12-07 13:27 UTC, mrbobbytables commented on content/en/blog/2021/contributor-celebration.md
> +2. **[The Great Cloud Native Bakeoff](https://www.youtube.com/watch?v=koT08purWDc)**
```suggestion
2. **[The Great Cloud Native Bakeoff](/events/kcc2021/activities/#krafternetes)**
```

2021-12-07 13:27 UTC, mrbobbytables commented on content/en/blog/2021/contributor-celebration.md
> +    **We’re looking for cooks of all backgrounds and talents.** If this sounds like fun to you and you want to cook with us, please fill the [form](https://docs.google.com/forms/d/e/1FAIpQLScmvXEFsdy
```suggestion
    **We’re looking for cooks of all backgrounds and talents.** If this sounds like fun to you and you want to cook with us, please fill the [form](https://docs.google.com/forms/d/e/1FAIpQLScmvXEFsdy0NzQofp198ShzupRPc4M5yDZYfdEMYPR4qD7aCw/viewform).
```

2021-12-07 13:27 UTC, mrbobbytables commented on content/en/blog/2021/contributor-celebration.md
> +More Information about the schedule could be found [here](/events/kcc2021/schedule/)
```suggestion
More Information about the schedule could be found [here](/events/kcc2021/schedule/).
```

2021-12-07 14:47 UTC, Debanitrkl commented
Thanks @mrbobbytables I have updated with the changes I guess it can be merged now

2021-12-07 14:59 UTC, mrbobbytables commented on content/en/blog/2021/contributor-celebration.md
> +date: 2021-12-06
```suggestion
date: 2021-12-07
```

2021-12-07 15:00 UTC, mrbobbytables commented
Thanks! 
/label tide/merge-method-squash
/approve
/hold

@jberkus can you do a double check for me?

2021-12-08 04:34 UTC, jberkus commented
/remove-hold
/lgtm

2021-12-08 04:35 UTC, merged