SIG Multicluster spotlight blog
kubernetes/contributor-site pull request #283
Opened 2022-01-28 19:15 UTC by dewan-ahmed

The blog resulting from this PR will serve as the canonical URL for the blog on kubernetes.io. [Details in the relevant PR](https://github.com/kubernetes/website/pull/31242) @sftim 

Once this PR is merged, I'll add a commit to [this PR](https://github.com/kubernetes/website/pull/31242) and add the canonical URL in the metadata.

2022-01-30 22:16 UTC, sftim requested changes
For _this_ site:

Please remove `2022-02-04-` from the Markdown file's name, so that it is:
`sig-multicluster-spotlight-blog.md`

All the inline feedback is nits (stuff that's nice to fix, but you don't have to).

2022-01-30 22:16 UTC, sftim commented on content/en/blog/2022/2022-02-04-sig-multicluster-spotlight-blog.md
> +My favortie example of "then vs. now" is cluster ID. A few years ago, there was an effort to define a cluster ID. A lot of really good thought went into this concept, for example, how do we make a cl
```suggestion
My favorite example of "then vs. now" is cluster ID. A few years ago, there was an effort to define a cluster ID. A lot of really good thought went into this concept, for example, how do we make a cluster ID is unique across multiple clusters. How do we make this ID globally unique so it'll work in every contact? Let's say, there's an acquisition or merger of teams - does the cluster IDs still remain unique for those teams?
```

2022-01-30 22:16 UTC, sftim commented on content/en/blog/2022/2022-02-04-sig-multicluster-spotlight-blog.md
> +[SIG Multicluster](https://github.com/kubernetes/community/tree/master/sig-multicluster) is the SIG focused on how Kubernetes concepts are expanded and used beyond the cluster boundary. Historically,
```suggestion
[SIG Multicluster](https://github.com/kubernetes/community/tree/master/sig-multicluster) is the Special Interest Group (SIG) focused on how Kubernetes concepts are expanded and used beyond the cluster boundary. Historically, Kubernetes resources only interacted within that boundary - KRU or Kubernetes Resource Universe (not an actual Kubernetes concept). Kubernetes clusters, even now, don't really know anything about themselves or, about other clusters. Absence of cluster identifiers is a case in point. With the growing adoption of multicloud and multicluster deployments, the work SIG Multicluster doing is gaining a lot of attention.

In this article, [Jeremy Olmsted-Thompson, Google](https://twitter.com/jeremyot) and [Chris Short, AWS](https://twitter.com/ChrisShort) discuss the interesting problems SIG Multicluster is solving and how you can get involved. Their initials **JOT** and **CS** will be used for brevity.
```

&hellip;explaining what SIG means, and also calling it an article. This is an article that appears in a blog - if you prefer using the word “blog” to mean both the set of articles and each individual article, you can omit that fix.

2022-01-30 22:16 UTC, sftim commented on content/en/blog/2022/2022-02-04-sig-multicluster-spotlight-blog.md
> +## Wrap Up
style nit:
```suggestion
## Wrap up
```

2022-02-02 20:07 UTC, dewan-ahmed commented
> For _this_ site:
> 
> Please remove `2022-02-04-` from the Markdown file's name, so that it is: `sig-multicluster-spotlight-blog.md`
> 
> All the inline feedback is nits (stuff that's nice to fix, but you don't have to).

Thanks @sftim fixed the file name and accepted suggested edits.

2022-02-02 20:55 UTC, jberkus commented
/lgtm
/approve

2022-02-02 20:58 UTC, merged