[WIP] Import and use the CNCF Code of Conduct
kubernetes/contributor-site pull request #421
Opened 2023-08-20 21:18 UTC by cblecker

This uses a generated import of the CNCF CoC

2023-08-20 21:24 UTC, sftim commented
Approach seems good to me.

2023-08-20 21:34 UTC, sftim commented
I'd expect to see 2 or more commits, one of which actually does the import.

2023-08-20 22:07 UTC, sftim commented
Want to put a Markdown file in source control but not have that render to its own web page? See https://github.com/kubernetes/website/pull/41793/files#diff-6837431359d119c18686bd0377481bf69921b81f4a221801d31e7fbe57aaa642 for an example of a way to do that:

```yaml
_build:
  list: never
  render: false
```

2023-08-20 22:58 UTC, cblecker commented
@sftim This should be ready for review. Thanks!

2023-08-21 01:48 UTC, mrbobbytables commented
> Want to put a Markdown file in source control but not have that render to its own web page? See https://github.com/kubernetes/website/pull/41793/files#diff-6837431359d119c18686bd0377481bf69921b81f4a221801d31e7fbe57aaa642 for an example of a way to do that:

Nice! I didn't know about that feature. 

Looks like a good method to pull this in and better than keeping a manual copy in repo 👍 
/approve

2023-08-21 08:11 UTC, sftim requested changes
Almost.
https://deploy-preview-421--kubernetes-contributor.netlify.app/includes/ exists, and I don't think it should.

A similar story for https://deploy-preview-421--kubernetes-contributor.netlify.app/includes/cncf-code-of-conduct/

2023-08-21 08:11 UTC, sftim commented on content/en/includes/_index.md
> +headless: true
```suggestion
headless: true
_build:
  list: never
  render: false
```

2023-08-21 14:25 UTC, sftim commented
https://deploy-preview-421--kubernetes-contributor.netlify.app/includes/cncf-code-of-conduct/ still renders. Not the end of the world IMO.

/lgtm
/hold

This is an improvement and I'm OK to live with the snag that remains.

2023-08-21 15:05 UTC, cblecker commented
/hold cancel

2023-08-21 15:07 UTC, merged