[WIP]: add 2024 kcseu skaffold page
kubernetes/contributor-site pull request #461
Opened 2023-12-05 00:14 UTC by moficodes

WIP:
fixes: #460

2023-12-05 13:41 UTC, mfahlandt commented on content/en/events/2024/kcseu/faq.md
> +TBD
19.04.2024

2023-12-05 13:44 UTC, mfahlandt commented on content/en/events/2024/kcseu/schedule.md
> +If you would like to submit a formal session, please use the [CFP Form]().
Remove Form for now and Replace with:

The CFP will open soon and will cover presentation, workshop, and collaboration style sessions.  
Unconference sessions should use the GitHub issue referenced above.

2023-12-05 15:32 UTC, natalisucks commented
@moficodes thanks for starting this, Mofi! our standard across Kubernetes docs is that page weights go up via an increment of 10 (see one issue this references regarding the need to update autogenerated code [#37486](https://github.com/kubernetes/website/issues/37486)). while we haven'g got this consistent throughout our docs yet, i'd say we ought to follow that standard for the contributor site

2023-12-05 23:40 UTC, jberkus requested changes

2023-12-05 23:40 UTC, jberkus commented on content/en/events/2024/kcseu/faq.md
> +No, based on our experience with Kubecon NA 2021, we do not expect to be able
```suggestion
No, based on our experience with Kubecon EU 2023, we do not expect to be able
```

2023-12-05 23:40 UTC, jberkus commented on content/en/events/2024/kcseu/faq.md
> +out community wide messages about it once the details are available.
```suggestion
We plan to include SIG meetings as part of the schedule for the Summit.  Please watch for the CfP, and submit your proposed SIG meeting as a Summit session.
```

2023-12-05 23:40 UTC, jberkus commented on content/en/events/2024/kcseu/schedule.md
> +TBD
```suggestion
The Summit will include Unconference sessions, probably in the afternoon.  If important discussions arise after the close of the CfP, plan to pitch them as Unconference sessions.  More details to come.
```

2023-12-05 23:40 UTC, jberkus commented on content/en/events/2024/kcseu/schedule.md
> +%}}
Should probably remove this block until it's live.

2023-12-05 23:40 UTC, jberkus commented on content/en/events/2024/kcseu/social.md
> +To bring a guest, please email community@kubernetes.io with their information.
```suggestion
More information on Guest registration to come, closer to the event.
```

2023-12-05 23:40 UTC, jberkus commented on content/en/events/2024/kcseu/social.md
> +TBD
```suggestion
The Summit will include a social event open only to Contributors (and their family members, see Guests below).  This event will take place somewhere near the Summit venue, and will include food, drink, entertainment, and games.  More information will be available once the venue is booked.

**Contributors must be registered for the Summit in order to attend the Social.**
```

2023-12-06 15:04 UTC, mrbobbytables requested changes
Thanks for stubbing it out, just have a few small changes to update for 2024 👍

2023-12-06 15:04 UTC, mrbobbytables commented on content/en/events/2024/kcseu/faq.md
> +
```suggestion
<li><a href="https://github.com/kubernetes-sigs" rel="noopener noreferrer" target="_blank">kubernetes-sigs</a></li>
<li><a href=“https://github.com/etcd-io” rel=“noopener noreferrer” target=“_blank”>etcd-io</a></li>
</ul>

```

etcd-io is now a k8s org

2023-12-06 15:04 UTC, mrbobbytables commented on content/en/events/2024/kcseu/faq.md
> +[email us]: mailto:community@kubernetes.io
```suggestion
[email us]: mailto:summit-team@kubernetes.io
```

2023-12-11 17:09 UTC, jberkus commented
@natalisucks we haven't done that with the Contributor Site, though.  We probably should, BUT that should be a separate PR from this one.  We could also think about trying to set things up so that we don't have to retro edit all the pages.  But again, I don't want to hold this PR on that.

2023-12-11 17:09 UTC, jberkus commented on content/en/events/2024/kcseu/schedule.md
> +%}}
@moficodes if you can fix this, then I can merge this PR.

2023-12-12 15:20 UTC, moficodes commented
@jberkus @mrbobbytables I think thats all the comments resolved.

2023-12-12 16:14 UTC, natalisucks commented
/lgtm
pushing this live ASAP is worthwhile then we can update other text/grammar fixes as needed

2023-12-13 00:41 UTC, jberkus commented
/approve
/lgtm

2023-12-13 00:44 UTC, merged